[tasks.wasm_clean]
script_runner = "@shell"
script = '''
rm -rf web/bin ||:
mkdir web/bin
'''

[tasks.format]
disabled = true

[tasks.test]
disabled = true

[tasks.crate]
command = "cargo"
args = ["build", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.build]
command = "wasm-bindgen"
args = [
    "--out-dir",
    "web\\bin",
    "--target",
    "web",
    "target\\wasm32-unknown-unknown\\release\\${CARGO_MAKE_CRATE_NAME}.wasm",
]
dependencies = ["wasm_clean", "crate"]

[tasks.serve]
command = "miniserve"
args = ["web", "--port", "17645", "--index", "index.html"]
dependencies = ["wasm"]
