[tasks.wasm_clean]
script_runner = "@shell"
script = '''
rm -f web/bin
'''

[tasks.build]
command = "cargo"
args = [
    "build",
    "--release",
    "--target",
    "wasm32-unknown-unknown",
    "--target-dir",
    "target",
]

[tasks.wasm]
command = "wasm-bindgen"
args = [
    "--out-name",
    "${CARGO_MAKE_CRATE_NAME}",
    "--out-dir",
    "web/bin",
    "--target",
    "web",
    "target/wasm32-unknown-unknown/release/${CARGO_MAKE_CRATE_NAME}.wasm",
]
dependencies = ["wasm_clean", "build"]

[tasks.serve]
command = "miniserve"
args = ["web", "--port", "17645", "--index", "index.html"]
dependencies = ["wasm"]
