name: web

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.markdown"
      - ".vscode/**"
      - "LICENCE"
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: true
      
      - name: Setup Pages
        if: ${{ !env.ACT }}
        id: pages
        uses: actions/configure-pages@v2
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - uses: davidB/rust-cargo-make@v1
        with:
          version: '0.36.1'

      - uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: '0.2.83'
      
      - name: ⚡ Cache
        if: ${{ !env.ACT }}
        uses: Swatinem/rust-cache@v2.0.0

      - name: Build
        run: cargo make --disable-check-for-updates --makefile makefile.toml 

      - name: Upload Artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./web
  
  deploy-pages:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
